[phases.setup]
nixPkgs = [
    "...",
    "chromium",
    "nss",
    "atk",
    "cups",
    "libdrm",
    "libxkbcommon",
    "pango",
    "mesa",
    "alsa-lib",
    "libXcomposite",
    "libXdamage",
    "libXrandr",
    "gbm"
]

[phases.install]
cmds = [
    "...",
    "PUPPETEER_SKIP_DOWNLOAD=true PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci --prefix vendor/kstmostofa/laravel-whatsapp/sidecar"
]

[start]
cmd = "sh ./scripts/railway-start.sh"
