<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // 1. Makanan Utama (Category ID: 1)
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Bibimbap Spesial',
                'description' => 'Nasi campur khas Korea dengan aneka sayuran segar, irisan daging sapi bulgogi, telur mata sapi, dan saus gochujang otentik.',
                'image' => null,
                'price' => 38000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'name' => 'Beef Bulgogi Rice Bowl',
                'description' => 'Nasi hangat dengan irisan daging sapi empuk yang dimarinasi saus manis gurih wijen khas Korea bertabur daun bawang.',
                'image' => null,
                'price' => 42000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'name' => 'Kimchi Bokkeumbap',
                'description' => 'Nasi goreng kimchi pedas aromatik khas Korea berpadu potongan sosis sapi, nori renyah, dan telur mata sapi setengah matang.',
                'image' => null,
                'price' => 30000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],
            [
                'id' => 4,
                'category_id' => 1,
                'name' => 'Jajangmyeon',
                'description' => 'Mie kenyal segar disiram saus chunjang kedelai hitam gurih manis pekat dengan irisan daging sapi dan timun segar.',
                'image' => null,
                'price' => 35000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'name' => 'Japchae Beef',
                'description' => 'Tumis soun ubi jalar Korea (dangmyeon) dengan sayuran warna-warni, irisan daging sapi, dan aroma minyak wijen harum.',
                'image' => null,
                'price' => 36000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'name' => 'Dakgalbi Rice Bowl',
                'description' => 'Nasi hangat disajikan bersama potongan ayam berbumbu saus pedas manis gochujang khas Chuncheon dengan taburan biji wijen.',
                'image' => null,
                'price' => 34000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],

            // 2. Korean Street Food (Category ID: 2)
            [
                'id' => 7,
                'category_id' => 2,
                'name' => 'Tteokbokki Spesial',
                'description' => 'Kue beras kenyal saus pedas manis gochujang bertabur wijen disajikan lengkap dengan kue ikan (odeng) dan telur rebus.',
                'image' => null,
                'price' => 25000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'name' => 'Rose Tteokbokki',
                'description' => 'Tteokbokki kekinian dengan perpaduan saus gochujang, susu, krim kental gurih, dan lelehan keju mozarella.',
                'image' => null,
                'price' => 32000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],
            [
                'id' => 9,
                'category_id' => 2,
                'name' => 'Odeng / Eomuk Tang',
                'description' => 'Tusukan kue ikan khas Korea yang empuk dan gurih disajikan dengan kuah kaldu panas kaya rasa daun bawang dan lobak.',
                'image' => null,
                'price' => 15000,
                'weight_or_unit' => '2 Tusuk',
                'is_active' => true,
            ],
            [
                'id' => 10,
                'category_id' => 2,
                'name' => 'Corndog Mozarella Full',
                'description' => 'Corndog renyah isi keju mozarella meleleh mulur berbalut adonan krispi dengan cocolan saus tomat, sambal, dan mayones.',
                'image' => null,
                'price' => 18000,
                'weight_or_unit' => '1 Pcs',
                'is_active' => true,
            ],
            [
                'id' => 11,
                'category_id' => 2,
                'name' => 'Corndog Sosis Mozarella',
                'description' => 'Kombinasi sosis sapi premium dan keju mozarella gurih dalam balutan adonan renyah bertabur sedikit gula bubuk halus.',
                'image' => null,
                'price' => 20000,
                'weight_or_unit' => '1 Pcs',
                'is_active' => true,
            ],
            [
                'id' => 12,
                'category_id' => 2,
                'name' => 'Yangnyeom Chicken',
                'description' => 'Ayam krispi tanpa tulang berbalut saus pedas manis karamel khas Korea dengan cita rasa gurih nagih.',
                'image' => null,
                'price' => 35000,
                'weight_or_unit' => '5 Pcs',
                'is_active' => true,
            ],
            [
                'id' => 13,
                'category_id' => 2,
                'name' => 'Honey Butter Chicken',
                'description' => 'Ayam goreng krispi renyah dibalut bumbu mentega madu manis harum khas Korea.',
                'image' => null,
                'price' => 35000,
                'weight_or_unit' => '5 Pcs',
                'is_active' => true,
            ],
            [
                'id' => 14,
                'category_id' => 2,
                'name' => 'Gimmari Crispy',
                'description' => 'Gorengan rumput laut lembaran gulung isi bihun bumbu gurih yang digoreng garing renyah keemasan.',
                'image' => null,
                'price' => 16000,
                'weight_or_unit' => '4 Pcs',
                'is_active' => true,
            ],
            [
                'id' => 15,
                'category_id' => 2,
                'name' => 'Mandu Goreng',
                'description' => 'Pangsit ala Korea berisi olahan daging cincang dan sayuran segar bertekstur kulit renyah garing.',
                'image' => null,
                'price' => 20000,
                'weight_or_unit' => '4 Pcs',
                'is_active' => true,
            ],

            // 3. Sup & Jjigae (Category ID: 3)
            [
                'id' => 16,
                'category_id' => 3,
                'name' => 'Sundubu Jjigae',
                'description' => 'Sup tahu sutra lembut berkuah merah pedas gurih kaya kaldu dengan telur setengah matang dan potongan seafood.',
                'image' => null,
                'price' => 38000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],
            [
                'id' => 17,
                'category_id' => 3,
                'name' => 'Kimchi Jjigae',
                'description' => 'Sup fermentasi kimchi asam pedas otentik Korea berpadu dengan tahu, jamur enoki, dan potongan daging sapi.',
                'image' => null,
                'price' => 38000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],
            [
                'id' => 18,
                'category_id' => 3,
                'name' => 'Doenjang Jjigae',
                'description' => 'Sup pasta kedelai fermentasi gurih hangat dengan labu, tahu, jamur, dan cabai hijau khas rumahan Korea.',
                'image' => null,
                'price' => 32000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],
            [
                'id' => 19,
                'category_id' => 3,
                'name' => 'Miyeok Guk',
                'description' => 'Sup rumput laut kuah kaldu sapi bening gurih menyehatkan, sering disajikan pada perayaan ulang tahun di Korea.',
                'image' => null,
                'price' => 25000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],

            // 4. Banchan & Side Dish (Category ID: 4)
            [
                'id' => 20,
                'category_id' => 4,
                'name' => 'Kimchi Baechu Segar',
                'description' => 'Kimchi sawi putih segar buatan sendiri hasil fermentasi dengan bumbu cabai gochugaru asli Korea.',
                'image' => null,
                'price' => 12000,
                'weight_or_unit' => '150 gr',
                'is_active' => true,
            ],
            [
                'id' => 21,
                'category_id' => 4,
                'name' => 'Danmuji',
                'description' => 'Acar lobak kuning manis renyah khas Korea yang sempurna sebagai penetral rasa pedas.',
                'image' => null,
                'price' => 8000,
                'weight_or_unit' => '100 gr',
                'is_active' => true,
            ],
            [
                'id' => 22,
                'category_id' => 4,
                'name' => 'Kkakdugi',
                'description' => 'Kimchi lobak putih potong dadu bertekstur krispi renyah dengan cita rasa pedas asam segar.',
                'image' => null,
                'price' => 12000,
                'weight_or_unit' => '150 gr',
                'is_active' => true,
            ],
            [
                'id' => 23,
                'category_id' => 4,
                'name' => 'Seasoned Gim (Rumput Laut)',
                'description' => 'Lembaran nori rumput laut panggang renyah bertabur minyak wijen aromatik dan sedikit garam laut.',
                'image' => null,
                'price' => 6000,
                'weight_or_unit' => '1 Bungkus',
                'is_active' => true,
            ],
            [
                'id' => 24,
                'category_id' => 4,
                'name' => 'Nasi Putih Hangat',
                'description' => 'Nasi putih pulen hangat disajikan dalam mangkuk mangkok stainless khas Korea.',
                'image' => null,
                'price' => 6000,
                'weight_or_unit' => '1 Porsi',
                'is_active' => true,
            ],

            // 5. Minuman (Category ID: 5)
            [
                'id' => 25,
                'category_id' => 5,
                'name' => 'Korean Strawberry Milk',
                'description' => 'Susu segar dingin creamy berpadu selai strawberry buatan rumah dengan bulir buah asli yang melimpah.',
                'image' => null,
                'price' => 18000,
                'weight_or_unit' => '1 Cup (350ml)',
                'is_active' => true,
            ],
            [
                'id' => 26,
                'category_id' => 5,
                'name' => 'Banana Uyu (Korean Banana Milk)',
                'description' => 'Susu rasa pisang manis lembut ikonik khas Korea yang sangat disukai semua kalangan.',
                'image' => null,
                'price' => 16000,
                'weight_or_unit' => '1 Cup (350ml)',
                'is_active' => true,
            ],
            [
                'id' => 27,
                'category_id' => 5,
                'name' => 'Yuzu Honey Iced Tea',
                'description' => 'Es teh seduh menyegarkan dipadu sari buah jeruk yuja Korea dan madu murni manis alami.',
                'image' => null,
                'price' => 16000,
                'weight_or_unit' => '1 Cup (400ml)',
                'is_active' => true,
            ],
            [
                'id' => 28,
                'category_id' => 5,
                'name' => 'Oksusu-cha (Teh Rambut Jagung)',
                'description' => 'Teh seduh rambut jagung tradisional Korea yang harum wangi, bebas kafein, dan sangat menyegarkan tenggorokan.',
                'image' => null,
                'price' => 10000,
                'weight_or_unit' => '1 Gelas',
                'is_active' => true,
            ],
            [
                'id' => 29,
                'category_id' => 5,
                'name' => 'Boricha (Es Teh Barley Korea)',
                'description' => 'Teh gandum barley panggang khas Korea disajikan dingin, beraroma nutty dan tanpa pemanis buatan.',
                'image' => null,
                'price' => 8000,
                'weight_or_unit' => '1 Gelas',
                'is_active' => true,
            ],
            [
                'id' => 30,
                'category_id' => 5,
                'name' => 'Es Kopi Dalgona',
                'description' => 'Kopi kocok berbusa karamel kental yang disajikan di atas susu segar dingin creamy.',
                'image' => null,
                'price' => 20000,
                'weight_or_unit' => '1 Cup (350ml)',
                'is_active' => true,
            ],
            [
                'id' => 31,
                'category_id' => 5,
                'name' => 'Air Mineral Dingin',
                'description' => 'Air mineral kemasan botol 600ml disajikan dingin menyegarkan.',
                'image' => null,
                'price' => 5000,
                'weight_or_unit' => '1 Botol (600ml)',
                'is_active' => true,
            ],

            // 6. Dessert (Category ID: 6)
            [
                'id' => 32,
                'category_id' => 6,
                'name' => 'Bingsu Matcha Red Bean',
                'description' => 'Es serut susu salju selembut kapas dengan bubuk matcha premium, pasta kacang merah manis, dan mochi kenyal.',
                'image' => null,
                'price' => 28000,
                'weight_or_unit' => '1 Mangkuk',
                'is_active' => true,
            ],
            [
                'id' => 33,
                'category_id' => 6,
                'name' => 'Bingsu Choco Oreo',
                'description' => 'Es serut salju susu dengan remahan biskuit Oreo melimpah, es krim vanila lembut, dan siraman cokelat lezat.',
                'image' => null,
                'price' => 28000,
                'weight_or_unit' => '1 Mangkuk',
                'is_active' => true,
            ],
            [
                'id' => 34,
                'category_id' => 6,
                'name' => 'Hotteok Cinnamon Brown Sugar',
                'description' => 'Pancake goreng ala Korea berisi lelehan gula cokelat, kacang kenari renyah, dan wangi kayu manis hangat.',
                'image' => null,
                'price' => 15000,
                'weight_or_unit' => '2 Pcs',
                'is_active' => true,
            ],
            [
                'id' => 35,
                'category_id' => 6,
                'name' => 'Hotteok Mozarella Cheese',
                'description' => 'Pancake kenyal hangat berisi lelehan keju mozarella gurih manis yang mulur saat digigit.',
                'image' => null,
                'price' => 18000,
                'weight_or_unit' => '2 Pcs',
                'is_active' => true,
            ],
        ];

        foreach ($products as $productData) {
            Product::updateOrCreate(
                ['id' => $productData['id']],
                $productData
            );
        }
    }
}
